QGIS-Contribution/QGIS-ResourceSharing

symbology_sharing/collection_manager.py, symbology_sharing/gui/qgs_symbology_sharing_dialog.py
Hi @elpaso,
I basically made a worker and move it to thread. The worker is responsible for downloading and installing the collection.
=> New approach to deal with thread

resource_sharing/repository_handler/base.py
=> Avoid breaking on incompatible versions

_posts/2016-07-22-what-to-share.md, _posts/2016-08-09-installing-collection.md
Some words about the R support added in #62.
It would be nice if someone could update the illustration of the directory structure in the "Repository Structure" section to include the ``rscripts`` directory.
=> R support documentation

resource_sharing/plugin.py
=> Make sure that the Resource Sharing action is included in the toolbar

README.md, resource_sharing/collection_manager.py, resource_sharing/custom_logging.py, resource_sharing/network_manager.py, resource_sharing/repository_handler/base.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_handler/remote_zip_handler.py
Sets QGIS levels that correspond to the Python logger levels.
Fixes: #71.
=> Update logger to use appropriate levels

_posts/2016-08-12-plugin-configuration.md
=> Document the setting for the collection directory location

resource_sharing/plugin.py
Fixes: #68
Prepares for fixing #28
=> Add the plugin to the web menu

resource_sharing/resource_handler/__init__.py, resource_sharing/resource_handler/model_handler.py
Fixes: #42
Documentation in #75.
I have added a model in the ``model`` directory of the collection ``R-scripts-QGIS2`` ("QGIS R script collection (from QGIS 2)") in the repository https://github.com/havatv/qgis_rscripts.git that can be used for testing.
=> Add a handler for processing models

_posts/2016-07-22-repository-structure.md, _posts/2016-07-22-what-to-share.md, _posts/2016-08-09-installing-collection.md
=> Document model support

resource_sharing/repository_handler/remote_git_handler.py
I tried to look around a bit, and found:
``https://github.com/dulwich/dulwich/issues/584``
Fixes: #80
=> Close repository after cloning to avoid WinErr 32

test/data/collections/test_collection/style/style_with_svg.qml, test/data/collections/test_collection/style/style_with_svg_other_collection.qml
=> PyQt4 -> qgis.PyQt

resource_sharing/repository_manager.py
Change from exception to warning.
Fixes #64.
=> Lower the logging level for missing name or URL in directory

resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/network_manager.py, resource_sharing/repository_handler/base.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/version_compare.py
Use error messages instead of exceptions
=> Avoid exceptions and adjust logging

resource_sharing/gui/resource_sharing_dialog.py
=> Disable edits of official repositories

resource_sharing/gui/resource_sharing_dialog.py
=> Clear the metadata page when a plugin is installed (#104)

README.md, metadata.txt, resource_sharing/collection_manager.py, resource_sharing/config.py, resource_sharing/exception.py, resource_sharing/gui/manage_dialog.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/network_manager.py, resource_sharing/plugin.py, resource_sharing/repository_handler/base.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_handler/remote_zip_handler.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/base.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py, resource_sharing/resource_handler/symbol_resolver_mixin.py, resource_sharing/symbol_xml_extractor.py, resource_sharing/utilities.py, resources/template/collection_details.html
Fix SVG counting.
Include resource summary for installed collections.
=> Remove svg uninstall

resource_sharing/resource_handler/symbol_handler.py
Update symbol_handler.py to use the symbol_type parameter, and not SymbolEntity(!)
Fixes #118.
=> Use the symbol_type parameter instead of SymbolEntity

resource_sharing/repository_manager.py
Handle renaming as a special case when editing repositories in Settings.
=> Simplify renaming of repositories

metadata.txt, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/resource_handler/symbol_handler.py
Handle version specific capabilities for Styles.
Try another solution for avoiding [WinError 5] (always cloning - never pulling github repositories)
Fix #127
Fix #103
=> Symbolxml 3.4

resource_sharing/collection_manager.py, resource_sharing/gui/manage_dialog.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/plugin.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/base.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py, resource_sharing/resource_handler/symbol_resolver_mixin.py, resource_sharing/utilities.py
Change directory / file structure handling from os.path to Path (pathlib).
=> Switch to pathlib

metadata.txt, resource_sharing/collection_manager.py, resource_sharing/config.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/__init__.py, resource_sharing/resource_handler/expression_handler.py, resource_sharing/utilities.py
Fix #130.
Documentation updated in #131.
=> Startup - expressions

_posts/2016-07-22-repository-structure.md, _posts/2016-07-22-what-to-share.md, _posts/2016-08-09-creating-repository.md, _posts/2016-08-09-installing-collection.md
Documentation of expression support (#130).
=> Introduce expressions (documentation)

resource_sharing/resource_handler/svg_handler.py
=> Change svgpath handling

resource_sharing/gui/resource_sharing_dialog.py
Use a different colour and style for the font of installed collections.
=> Differentiate better between repos and collections in the settings dialogue

metadata.txt, resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/gui/ui/resource_sharing_dialog_base.ui, resource_sharing/plugin.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/base.py, resource_sharing/resource_handler/expression_handler.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py, resource_sharing/resource_handler/symbol_resolver_mixin.py, resource_sharing/symbol_xml_extractor.py, resource_sharing/utilities.py
GUI improvements (emphasizing repositories with installed collections, repositories in the QGIS directory and installed collections).
Fix handling of QGIS directory updates (fix: #146)
New button for reloading the QGIS directory (fix: #145)
Code clean-up (pep8, ...)
=> GUI improvements, fix handling of QGIS directory updates and new button for reloading the QGIS directory

CONTRIBUTORS, metadata.txt, resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/resource_handler/__init__.py, resource_sharing/resource_handler/checklist_handler.py, resource_sharing/utilities.py
This PR adds support for resources of type **Checklist**.
It follows the discussion raised in #151.
The proposed changes add a new `ChecklistHandler` which is able to copy checklist JSON files into the user's {profile-dir}/checklists directory, where these become usable by the [QGIS Dataset QA Workbench] plugin.
Closes #151
[QGIS Dataset QA Workbench]: https://github.com/kartoza/qgis_dataset_qa_workbench/
=> Add support for Checklist resources

metadata.txt, resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/resource_handler/checklist_handler.py, resource_sharing/utilities.py
File related fixes to the checklist handler plus some formatting
=> File related fixes to the checklist handler plus some formatting and preparations for new version

_posts/2016-07-22-repository-structure.md, _posts/2016-07-22-what-to-share.md
This PR adds some small changes to the docs to mention the new checklist resource
=> Add documentation for checklist resource type

CONTRIBUTING.md
=> Typo fix CONTRIBUTING.md

.github/labeler.yml, docs/development/translation.md, resource_sharing/gui/ui/download_dialog.ui, resource_sharing/gui/ui/manage_repository.ui, resource_sharing/gui/ui/resource_sharing_dialog_base.ui, resource_sharing/resources/i18n/plugin_translation.pro, resource_sharing/resources/i18n/qgis_resource_sharing_fr.ts
- add Qt translation configuration (`plugin_translation.pro`)
- add a partial French translation
=> Add i18n for plugin UI

qgis_resource_sharing/metadata.txt
Just to find it if someone copy/paste "resources" in the QGIS plugin manager.
=> Update metadata.txt about tags

qgis_resource_sharing/metadata.txt, tests/unit/test_plg_metadata.py
Since OSGeo4W broke LTR shipped Python version without any discussion...
=> update(packaging): set QGIS maximum version 

docs/authoring/creating-metadata.md
As mentioned in: https://github.com/qgis/QGIS-Resources/issues/59
=> Fix typo: collection -> collections
