resource_sharing/repository_handler/__init__.py, resource_sharing/repository_handler/base.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_zip_handler.py
Hi @elpaso, this is working using zip handler. To use zip handler, you need to set the repo URI like this example:
Repo: ```http://localhost:63342/zip_data_example/```. Users need to put the metadata in this URI: ```http://localhost:63342/zip_data_example/metadata.ini``` and the collection in this URI ```http://localhost:63342/zip_data_example/collections/<collection_name>.zip```
It doesn't support custom collection URI yet and still using the old repository handlers (not refactoring it into metadata handler and collection handler)
=> Remote ZIP handler

ext_libs/giturlparse/platforms/__init__.py, ext_libs/giturlparse/platforms/gogs.py, ext_libs/giturlparse/result.py, resource_sharing/repository_handler/__init__.py, resource_sharing/repository_handler/gitlab_handler.py, resource_sharing/repository_handler/gogs_handler.py, test/repository_handler/test_handler.py
This will also support git.osgeo.org/gogs repositories.
=> [FEATURE] add support for gitlab and gogs repositories

metadata.txt, resource_sharing/collection_manager.py
Necessary for QGIS 3, since it uses Python 3.
Here is the error message that this PR addresses:
The error message will appear if you try to delete a repository in "Settings".
Fixes #59.
=> Change iteritems() to items() to avoid "crash" when deleting a repository

resource_sharing/utilities.py
Adds a setting ('localCollectionDir') under [ResourceSharing] to ``QGIS.ini`` that contains the file system location of the root directory of the collections. This allows users to change the file system location of the collections (as requested in #51).
Also, the new default location is "collections" under the ``resource_sharing`` directory in the user's QGIS directory (hidden - on Ubuntu:
``~/.local/share/QGIS/QGIS3/profiles/default/resource_sharing/collections``,
on Windows:
``C:\Users\<USER>\AppData\Roaming\QGIS\QGIS3\profiles\default\resource_sharing\collections``
-- alongside the "resources" directory and the repository cache).
To avoid problems for existing installations:
0. The default is to set 'localCollectionDir' to the new default location, but there are exceptions...
1. The …
=> Allow the user to define the location of the collections in the file system

resource_sharing/repository_manager.py
Make the plugin a bit more safe by protecting against Null.
Fixes:  #64.
=> Check for missing repository name and URL in directory

resource_sharing/custom_logging.py
The logger name needs to be consistent for the logging to work.
=> Use correct name (uppercase in "sharing") for logger

resource_sharing/repository_handler/remote_git_handler.py
A hack (using `warnings.filterwarnings`) to avoid `ResourceWarning` when using *dulwich* / *Porcelain* to download github repositories.
Fix #95.
=> Simple fix to avoid ResourceWarning

resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py, resource_sharing/resource_handler/symbol_resolver_mixin.py
The "resource handlers" now count the number of objects installed, and a summary is presented in a message box after installation is complete.
Fixes #6.
Fixes #101 (avoid creating "parent" tag in QGIS 3).
Comments have been updated, and the Processing script uninstall function has been updated (same behaviour as for R scripts).
=> Provide installation summary after collection installation

metadata.txt, resource_sharing/repository_handler/remote_git_handler.py
Dulwich/porcelain does not handle file removal (https://github.com/dulwich/dulwich/issues/452, https://github.com/dulwich/dulwich/issues/588). To ensure that the collection directory of remote repository is mirrored locally when a collection is reinstalled, the collection directory is removed before pulling.
Fixes #44.
=> Manual file/directory removal before pull

resource_sharing/resource_handler/symbol_handler.py
Updated symbol_handler.py so that colormaps and symbols get more user friendly identifiers.
Fixes: #116.
=> Use repository name instead of hash for symbol identifiers

resource_sharing/resource_handler/symbol_handler.py, resource_sharing/symbol_xml_extractor.py
Add support for style labelsettings and textformats.
Fixes:  #113
Fixes: #114
=> Improve style support

resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py
Fix of issues (crashes) resulting from the move to pathlib.
=> Fix uninstall

resources/template/collection_details.html, resources/template/tab_description.html
GUI updates: Collection metadata order, preview scroll issue, padding/margins.
Fix #138, fix #139, fix #140 (partly), fix #141.
=> GUI updates - metadata order, preview scroll issue, padding/margins

_posts/2016-07-25-creating-metadata.md
Update the documentation to say that email is optional (used to be mandatory)
Issue: #140
=> Make email optional in the metadata

metadata.txt, resource_sharing/collection_manager.py, resource_sharing/gui/resource_sharing_dialog.py, resource_sharing/gui/ui/resource_sharing_dialog_base.ui, resource_sharing/plugin.py, resource_sharing/repository_handler/filesystem_handler.py, resource_sharing/repository_handler/remote_git_handler.py, resource_sharing/repository_manager.py, resource_sharing/resource_handler/base.py, resource_sharing/resource_handler/expression_handler.py, resource_sharing/resource_handler/model_handler.py, resource_sharing/resource_handler/processing_handler.py, resource_sharing/resource_handler/r_handler.py, resource_sharing/resource_handler/style_handler.py, resource_sharing/resource_handler/svg_handler.py, resource_sharing/resource_handler/symbol_handler.py, resource_sharing/resource_handler/symbol_resolver_mixin.py, resource_sharing/symbol_xml_extractor.py, resource_sharing/utilities.py
Add button for reloading the QGIS directory of approved resources (#145).
Fix bug in the handling of QGIS directory updates (#146).
=> Enablereloading the directory (and some formatting updates)

.github/workflows/documentation.yml, requirements/documentation.txt
In this PR :
- rely on modern GitHub Pages deployment through GitHub Actions instead of pushing to a specific branch (gh-pages). A cleaner behavior, similar to GitLab Pages.
- improve documentation workflow to build also on PR but not deploy
- remove ghp-import dependency since it's not necessary anymore
After merging this one, remember to remove gh-pages branch and switch to beta GitHub Actions in https://github.com/QGIS-Contribution/QGIS-ResourceSharing/settings/pages
=> docs: use new GitHub Pages workflow instead of gh-pages branch

qgis_resource_sharing/gui/resource_sharing_dialog.py, qgis_resource_sharing/repository_handler/base.py, qgis_resource_sharing/repository_handler/filesystem_handler.py, qgis_resource_sharing/repository_handler/remote_git_handler.py, qgis_resource_sharing/repository_handler/remote_zip_handler.py
This shadows the builtin keyword `id`.
=> Do not use reserved keyword id as a function parameter

.github/workflows/build_release.yml
see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> update(ci): rm reference to set-output

.github/workflows/build_release.yml, .github/workflows/documentation.yml, .github/workflows/linter.yml, .github/workflows/tester.yml, .pre-commit-config.yaml
Since QGIS changed his shipped Python version from 3.9 to 3.12 without any warning and in the middle of a LTR cycle (between 3.34.5 and 3.34.6) and giving that plugin embeds some external dependency ([dulwich](https://github.com/jelmer/dulwich)), we have to align Python version with the used in QGIS.
Note: I've to use Python 3.11 for the translation job only since pyqt5-tools is still not compatible with upper versions (see https://github.com/altendky/pyqt-tools/issues/132).
=> update(ci): use Python 3.12 to fit QGIS shipped version

qgis_resource_sharing/metadata.txt
Needed because of rough change of shipped Python version in QGIS LTR for Windows... :man_facepalming:
=> update(packaging): bump minimal QGIS version to 3.34.6
